Adds a nvhpc 25.5 dockerfile

diff --git a/Dockerfile-base-ubuntu24.04-nvhpc25.5 b/Dockerfile-base-ubuntu24.04-nvhpc25.5
--- a/Dockerfile-base-ubuntu24.04-nvhpc25.5
+++ b/Dockerfile-base-ubuntu24.04-nvhpc25.5
@@ -1,7 +1,7 @@
 ####################################################################################################
 # Dockerfile for building a scientific HPC base image on Ubuntu 24.04 with NVIDIA Grace Hopper (ARM64)
 #
-# - Base image: nvcr.io/nvidia/nvhpc:24.11-devel-cuda12.6-ubuntu24.04 (AArch64, CUDA 12.6, NVHPC 24.11)
+# - Base image: nvcr.io/nvidia/nvhpc:25.5-devel-cuda12.9-ubuntu24.04 (AArch64, CUDA 12.9, NVHPC 25.5)
 # - Installs essential build tools, Python 3, and scientific libraries
 # - Clones and bootstraps Spack (v0.23.1) for flexible package management
 # - Configures Spack environment with mirrors for faster binary installs and externalizes system tools
@@ -13,7 +13,7 @@
 #
 # Intended for use as a base image for scientific/HPC workflows targeting NVIDIA Grace Hopper platforms.
 ####################################################################################################
-FROM nvcr.io/nvidia/nvhpc:24.11-devel-cuda12.6-ubuntu24.04 as builder
+FROM nvcr.io/nvidia/nvhpc:25.5-devel-cuda12.9-ubuntu24.04 as builder
 ############## Set up build environment#################
 # Add packages needed for building software stack 
 RUN sed -i -e 's/http:/https:/g' /etc/apt/sources.list.d/ubuntu.sources
@@ -53,29 +53,29 @@ set -o noclobber \
 &&   echo '    e4s-arm: https://cache.e4s.io/23.11/arm64'\
 &&   echo '  definitions:' \
 &&   echo '  - packages_builtin:' \
-&&   echo '    - bacio%nvhpc@24.11' \
-&&   echo '    - hdf5@1.14.3%nvhpc@24.11+fortran+hl+szip~mpi' \
-&&   echo '    - ip%nvhpc@24.11' \
-&&   echo '    - libyaml@0.2.5%nvhpc@24.11' \
-&&   echo '    - nccmp@1.9.1.0%nvhpc@24.11' \
-&&   echo '    - netcdf-c@4.9.2%nvhpc@24.11~mpi~dap' \
-&&   echo '    - netcdf-fortran@4.6.1%nvhpc@24.11' \
-&&   echo '    - sp@2.3.3%nvhpc@24.11' \
-&&   echo '    - w3emc@2.11.0%nvhpc@24.11' \
-&&   echo '    - w3nco@2.4.1%nvhpc@24.11' \
-&&   echo '    - zlib%nvhpc@24.11' \
-&&   echo '    - zlib-ng@2.1.4%nvhpc@24.11' \
-&&   echo '    - cuda@12.6.0' \
+&&   echo '    - bacio%nvhpc@25.5' \
+&&   echo '    - hdf5@1.14.3%nvhpc@25.5+fortran+hl+szip~mpi' \
+&&   echo '    - ip%nvhpc@25.5' \
+&&   echo '    - libyaml@0.2.5%nvhpc@25.5' \
+&&   echo '    - nccmp@1.9.1.0%nvhpc@25.5' \
+&&   echo '    - netcdf-c@4.9.2%nvhpc@25.5~mpi~dap' \
+&&   echo '    - netcdf-fortran@4.6.1%nvhpc@25.5' \
+&&   echo '    - sp@2.3.3%nvhpc@25.5' \
+&&   echo '    - w3emc@2.11.0%nvhpc@25.5' \
+&&   echo '    - w3nco@2.4.1%nvhpc@25.5' \
+&&   echo '    - zlib%nvhpc@25.5' \
+&&   echo '    - zlib-ng@2.1.4%nvhpc@25.5' \
+&&   echo '    - cuda@12.9.0' \
 &&   echo '  packages:' \
 &&   echo '    cuda:' \
 &&   echo '      externals:' \
-&&   echo '      - spec: "cuda@12.6.0"' \
-&&   echo '        prefix: "/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/cuda"' \
+&&   echo '      - spec: "cuda@12.9.0"' \
+&&   echo '        prefix: "/opt/nvidia/hpc_sdk/Linux_aarch64/25.5/cuda"' \
 &&   echo '      buildable: False' \
 &&   echo '    nvhpc:' \
 &&   echo '      externals:' \
-&&   echo '      - spec: "nvhpc@24.11"' \
-&&   echo '        prefix: "/opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers"' \
+&&   echo '      - spec: "nvhpc@25.5"' \
+&&   echo '        prefix: "/opt/nvidia/hpc_sdk/Linux_aarch64/25.5/compilers"' \
 &&   echo '      buildable: False' \
 &&   echo '    hdf5:' \
 &&   echo '      variants: +fortran+hl+szip~mpi' \
@@ -147,7 +147,7 @@ set -o noclobber \
 &&   echo '      target: [aarch64]' \
 &&   echo '      providers:' \
 &&   echo '        zlib-api: [zlib-ng+compat, zlib]' \
-&&   echo '      compiler: [nvhpc@24.11]' \
+&&   echo '      compiler: [nvhpc@25.5]' \
 &&   echo '  specs:' \
 &&   echo '  - matrix:' \
 &&   echo '    - [$packages_builtin]' \
@@ -213,18 +213,18 @@ RUN . /opt/spack/share/spack/setup-env.sh && \
 RUN . /opt/spack/share/spack/setup-env.sh && \
     cd /opt/spack-environment && \
     spack env activate . && \
-    (spack install bacio%nvhpc@24.11 || echo "bacio failed to install") && \
-    (spack install ip%nvhpc@24.11 || echo "ip failed to install") && \
-    (spack install sp@2.3.3%nvhpc@24.11 || echo "sp failed to install") && \
-    (spack install w3emc@2.11.0%nvhpc@24.11 || echo "w3emc failed to install") && \
-    (spack install w3nco@2.4.1%nvhpc@24.11 || echo "w3nco failed to install") && \
-    (spack install nccmp@1.9.1.0%nvhpc@24.11 || echo "nccmp failed to install") && \
+    (spack install bacio%nvhpc@25.5 || echo "bacio failed to install") && \
+    (spack install ip%nvhpc@25.5 || echo "ip failed to install") && \
+    (spack install sp@2.3.3%nvhpc@25.5 || echo "sp failed to install") && \
+    (spack install w3emc@2.11.0%nvhpc@25.5 || echo "w3emc failed to install") && \
+    (spack install w3nco@2.4.1%nvhpc@25.5 || echo "w3nco failed to install") && \
+    (spack install nccmp@1.9.1.0%nvhpc@25.5 || echo "nccmp failed to install") && \
     spack gc -y
 
 ENV LD_LIBRARY_PATH /opt/views/view/lib:$LD_LIBRARY_PATH
 ENV LIBRARY_PATH /opt/views/view/lib:$LIBRARY_PATH
 ENV PATH /opt/views/view/bin:$PATH
 ENV PKG_CONFIG_PATH /opt/views/view/lib/pkgconfig
-ENV CUDA_HOME /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/cuda
-ENV NVHPC_ROOT /opt/nvidia/hpc_sdk/Linux_aarch64/24.11/compilers
+ENV CUDA_HOME /opt/nvidia/hpc_sdk/Linux_aarch64/25.5/cuda
+ENV NVHPC_ROOT /opt/nvidia/hpc_sdk/Linux_aarch64/25.5/compilers
 ENTRYPOINT [ "/bin/bash" ]
